> 常有人说 async 函数是 Generator 函数的语法糖，async/await 的行为就好像搭配使用了生成器和 promise。

## Generator

带星号的生成器函数，执行时遇到*yield*关键字，将返回关键字后面的内容，并暂停该函数的执行，可以通过*next*方法恢复执行。

```javascript
// 生成器函数
function* helloWorldGenerator() {
  const a = yield "hello"
  console.log("hello", a)
  const b = yield "world"
  console.log("world", b)
  return "ending"
}

// 调用生成器函数会返回一个 Generator 生成器实例对象
var hw = helloWorldGenerator()

// 调用生成器对象的 next 方法会执行函数到下一个 yield 关键字停止，并返回一个结果
// yield 后的值作为结果的 value，函数是否执行完毕作为结果的 done
console.log(hw.next("this is a")) // {value: "hello", done: false}
console.log(hw.next("this is b")) // {value: "world", done: false}
console.log(hw.next()) // {value: "ending", done: true}
console.log(hw.next()) // {value: undefined, done: true}

// 控制台输出
// next 方法的参数会作为上一次生成器函数 yield 关键字的返回值处理
// hello, this is a
// world, this is b
```

```javascript
function helloWorldGenerator() {
  var a, b
  return regeneratorRuntime.wrap(function helloWorldGenerator$(_context) {
    // while(1) 配合 return 没有任何实际意义
    // 编程中用来表示 while 中的内容会被执行多次
    while (1) {
      switch ((_context.prev = _context.next)) {
        case 0:
          _context.next = 2
          return "hello"

        case 2:
          a = _context.sent
          console.log("hello", a)
          _context.next = 6
          return "world"

        case 6:
          b = _context.sent
          console.log("world", b)
          return _context.abrupt("return", "ending")

        case 9:
        case "end":
          return _context.stop()
      }
    }
  }, _marked)
}

// 简易代码
const regeneratorRuntime = {
  mark(fn) {
    return fn
  },
  wrap(fn) {
    const _context = {
      prev: 0, // 表示下一次执行生成器函数 switch 的下表
      sent: "", // 保存 next 调用传入的参数
      done: false, // 是否完成
      stop() { // 完成函数
        this.done = true
      },
    }
    return {
      next(param) {
        // 修改上一次 yield 的返回值
        _context.sent = param
        // 执行函数，获得本次返回值
        const value = fn(_context)
        // 返回
        return {
          value,
          done: _context.done,
        }
      },
    }
  },
}
```

### 协程

比线程更加轻量级的存在，可视为线程上的任务，且不为内核管理，完全交由程序（用户）控制。

协程在主线程上交互执行，通过*yield*和*next*来配合。

### Generator 和协程的配合

1. 通过生成器函数创建一个协程，后协程没有立即执行
2. 需调用*next*执行协程
3. 协程执行中遇到*yield*关键字将暂停并返回主要信息给父协程
4. 协程执行中遇到*return*关键字则结束当前协程并返回*return*后内容给父协程

## async

async 函数*一定会返回一个 promise 对象*（如果一个 async 函数的返回值看起来不是 promise，那么它将会被隐式地包装在一个 promise 中）

```javascript
async function foo() {
   return 1
}
// 等价于
function foo() {
   return Promise.resolve(1)
}
---
async function foo() {
   await 1
}
// 等价于
function foo() {
   return Promise.resolve(1).then(() => undefined)
}
```

```javascript
function* testG() {}

function asyncToGenerator(generatorFunc) {
  // 采用高阶函数的方式实现
  return function () {
    // 先调用Generator函数，生成迭代器
    // var gen = testG()
    let gen = generatorFunc.apply(this, argments)

    // async函数默认返回的是promise对象，外部使用then或者await使用这个返回值
    // var test = asyncToGenerator(testG)
    // test.then(res => do something with res)
    return new Promise((resolve, reject) => {
      // 通过step函数来一步一步跨过yield阻碍（递归）
      // @param key: next | throw 对应gen的next和throw方法
      // @param arg 用来吧promise resolve的值交给下一个yield
      function step(key, arg) {
        let generatorResult

        // 通过trycatch把报错通过promise reject出去，外部通过catch来获取错误
        try {
          generatorResult = gen[key](arg)
        } catch (error) {
          return reject(error)
        }

        // gen.next()的返回结构是{ value, done }
        const { value, done } = generatorResult

        if (done) {
          // done是在最后一次调用next后才会为true
          // { value: value, done: true }
          // 完成后resolve这个promise
          // 这个value也是Generator函数最后的返回值
          return resolve(value)
        } else {
          // 遇到yield时自动调用gen.next()
          // { value: Promise, done: false }
          // value也可以不是promise，这里兼容处理成promise
          // 等待promise resolve后执行next
          return Promise.resolve(value).then(
            // 只要done不是true就会递归的往下解开promise
            (val) => step("next", val),
            // 如果promise被reject了
            // 再次进入step函数调用的时try里的gen.throw(err)
            // 之后自然就被catch到，然后把promise rejcet掉
            (err) => step("throw", err)
          )
        }
      }
      step("next")
    })
  }
}
```

#### 更优雅的使用 async

1. 并发

```javascript
;(async () => {
  // const list = await getList()
  // const anotherList = await getAnotherList()

  const listPromise = getList()
  const anotherListPromise = getAnotherList()
  await listPromise
  await anotherListPromise
})()

// Promise.all([...])
```

2. 遍历实现的继发与并发

```javascript
// 继发
async function loadData(urls) {
  for (const url of urls) {
    const response = await fetch(url)
    console.log(await response.text())
  }
}

// 并发
async function loadData(urls) {
  const textPromises = urls.map(async (url) => {
    const response = await fetch(url)
    return response.text()
  })

  for (const textPromise of textPromises) {
    console.log(await textPromise)
  }
}
```

3. 错误捕获

```javascript
// 优化使用trycatch捕获错误
function to(promise) {
    return promise.then(res => [null, res]).catch(err=>[err])
}

async function asyncTask() {
    let [err, data] = await to(promise)
    if (err) ...
    if (user) ...
}

// or

async function asyncTask() {
    let data = await promise.catch(err => {
        ...
    })
}
```

#### async & Promise & Generator

- async 是一种语法，Promise 是一个内置对象，两者不具可比性，何况 async 函数返回 Promise 对象。
- async 某些场景比 Promise 更优雅的处理异步流程，Pormise 提供 all 和 race 方法
- Promise 本身是一个对象，可以在代码中任意传递
- async 需要 Babel 编译（1000 行）
- async 是 Generator 处理异步方面比较 hack 的用法，两者本身用来解决不同的问题
